version: '2.1'

services:
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: on-failure
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - sush_platform_net
    healthcheck: 
      test:  mysql --user=root --password=password -e 'select * from vm_db.vm_reservations'

  vm-manager:
    depends_on:
      db: 
        condition: service_healthy
    links:
      - db
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - sush_platform_net

volumes:
  mysql_data:

networks:
  sush_platform_net:
    driver: bridge